# Generated by Django 5.1.4 on 2025-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_customcakeorder_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='berries',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='topping',
        ),
        migrations.AddField(
            model_name='customcake',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
