# Generated by Django 5.1.4 on 2025-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_remove_customcakeorder_berries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcake',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='order_number',
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='berries',
            field=models.CharField(blank=True, default='none', max_length=20, null=True, verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='decor',
            field=models.CharField(blank=True, default='none', max_length=20, null=True, verbose_name='Декор'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='levels',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Уровни'),
        ),
        migrations.AddField(
            model_name='customcakeorder',
            name='topping',
            field=models.CharField(blank=True, default='none', max_length=20, null=True, verbose_name='Топпинг'),
        ),
    ]
